<html>
    <head>
    </head>
    <body>
        <table style="width:600px;border-collapse:collapse;">
            <tr>
                <td style="text-align: center;background-color:#eee;padding:27px 0">
                    <img src="http://beta.bedandbreakfastinitaly.com/images/logo.png"/>
                </td>
            </tr>
            <?php /*<tr>
                <td style="background-color:#eee;font-size: 18px;text-align: center;font-style: italic;color:#666;font-family:'Georgia'">
                    ciao
                </td>
            </tr>
            <tr>
                <td style="background-color:#eee;font-size: 24px;text-align: center;font-style: italic;font-weight: bold;color:#666;font-family:'Georgia'">
                    Mario Rossi
                </td>
            </tr> 
            <tr>
                <td style="background-color:#eee;font-size: 24px;text-align: center;font-style: italic;font-weight: bold;color:#666;font-family:'Georgia';padding:18px 0;">
                    <img src="http://beta.bedandbreakfastinitaly.com/images/email-separator.jpg"/>
                </td>
            </tr> */?>
            <tr>
                <td style="background-color:#eee;font-size: 24px;text-align: center;font-style: italic;font-weight: bold;color:#666;font-family:'Georgia'">
                    Grazie
                </td>
            </tr> 
            <tr>
                <td style="background-color:#eee;font-size: 18px;text-align: left;font-style: italic;color:#333;font-family:'Georgia';padding:0 40px 25px;">
                    <br />
                    Sei appena entrato a far parte del network BBItaly.com!
                    <br/>
                    <br/>
                    questi sono i dati di accesso alla tua area riservata!
                    <br />
                    <br />
                    Email: <b><?php echo $this->email?></b>
                    <br />
                    <br />
                    Password :<b><?php echo $this->password?></b>
                </td>
            </tr>
            <tr>
                <td style="background-color:#eee;font-size: 18px;text-align: left;font-style: italic;font-weight: bold;color:#333;font-family:'Georgia';padding: 0;">
                    <img src="http://beta.bedandbreakfastinitaly.com/images/email-footer.jpg"/>
                </td>
            </tr>
            <tr>
                <td style="background-color:#333;font-size: 11px;text-align: center;color:#999;font-family:'Georgia';padding:0 20px 20px">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ante arcu, ultrices sit amet facilisis quis, tincidunt id urna. Nam feugiat felis at magna tincidunt ac suscipit ipsum gravida. Suspendisse et lacus tellus. Suspendisse potenti. Donec id nunc magna. Sed rhoncus
                </td>
            </tr>
        </table>
    </body>
</html>