HOST: http://localhost:8080/bbitaly

--- BBItaly ---

---
Documentazione delle API messe a disposizione dell'interfaccia di backed del sistema di gestione B&B.
---

--
Booking

Gestione delle prenotazioni.
--

Estrare una prenotazione
GET /book
< 200
< Content-Type: application/json

Crea una prenotazione
POST /book
< 200
< Content-Type: application/json

Estrare una prenotazione utilizzando come criterio di ricerca una *accomodation*
GET /book/byAccomodation
< 200
< Content-Type: application/json

Estrare una prenotazione utilizzando come criterio di ricerca una *room*
GET /book/byRoom
< 200
< Content-Type: application/json

Estrare una prenotazione utilizzando come criterio di ricerca un *user*
GET /book/byUser
< 200
< Content-Type: application/json

Controlla una prenotazione
GET /book/check
< 200
< Content-Type: application/json

Cancella una prenotazione
POST /book/delete
< 200
< Content-Type: application/json

Attiva una prenotazione
POST /book/activate
< 200
< Content-Type: application/json


-- Owner --

POST /owner
< 200
< Content-Type: application/json

GET /owner
< 200
< Content-Type: application/json

POST /owner/update
< 200
< Content-Type: application/json

POST /owner/delete
< 200
< Content-Type: application/json

-- Authorization --

GET /auth/owner
< 200
< Content-Type: application/json

GET /auth/user
< 200
< Content-Type: application/json

-- User --

Ottiene ottiene informazioni sull'utente corrente.
GET /user
< 200
< Content-Type: application/json

Crea una nuova utenza all'interno dell'applicativo.
POST /user
< 200
< Content-Type: application/json

Aggiorna una specifica utenza.
POST /user/update
< 200
< Content-Type: application/json

Cancella ua specifica utenza
POST /user/delete
< 200
< Content-Type: application/json

Attiva una specifica utenza.
POST /user/activate
< 200
< Content-Type: application/json


-- Information definition --

GET /country
< 200
< Content-Type: application/json

GET /region
< 200
< Content-Type: application/json

GET /city
< 200
< Content-Type: application/json


-- Monitoring --

GET /status
< 200
< Content-Type: application/json

GET /health
< 200
< Content-Type: application/json


-- Serch --

GET /solr
< 200
< Content-Type: application/json

GET /search
< 200
< Content-Type: application/json

GET /semantic
< 200
< Content-Type: application/json

GET /bycity
< 200
< Content-Type: application/json

GET /byregion
< 200
< Content-Type: application/json

GET /bypoi
< 200
< Content-Type: application/json

GET /bycoords
< 200
< Content-Type: application/json

GET /byids
< 200
< Content-Type: application/json

-- Bed and Breakfast --

GET /bb
< 200
< Content-Type: application/json

POST /bb
< 200
< Content-Type: application/json

POST /bb/update
< 200
< Content-Type: application/json

POST /bb/delete
< 200
< Content-Type: application/json

POST /bb/cover
< 200
< Content-Type: application/json

-- B&B Gallery --

GET /bb/gallery
< 200
< Content-Type: application/json

POST /bb/gallery/delete
< 200
< Content-Type: application/json

POST /bb/gallery/update
< 200
< Content-Type: application/json

POST /bb/gallery
< 200
< Content-Type: application/json


-- Search B&B --

GET /bb/byowner
< 200
< Content-Type: application/json

GET /bb/all
< 200
< Content-Type: application/json

GET /bb/allcount
< 200
< Content-Type: application/json

GET /bb/countbyonwer
< 200
< Content-Type: application/json

GET /bb/policy
< 200
< Content-Type: application/json

GET /bb/facility
< 200
< Content-Type: application/json


-- B&B Room --

POST /bb/room
< 200
< Content-Type: application/json

GET /bb/room
< 200
< Content-Type: application/json

GET /bb/room/byaccomodation
< 200
< Content-Type: application/json

POST /bb/room/delete
< 200
< Content-Type: application/json

POST /bb/room/price
< 200
< Content-Type: application/json

GET /bb/room/price
< 200
< Content-Type: application/json

GET /bb/room/pricetotal
< 200
< Content-Type: application/json

POST /bb/room/cover
< 200
< Content-Type: application/json

POST /bb/room/update
< 200
< Content-Type: application/json

GET /bb/room/gallery
< 200
< Content-Type: application/json

POST /bb/room/gallery
< 200
< Content-Type: application/json

POST /bb/room/gallery/update
< 200
< Content-Type: application/json


-- Translation --

GET /translation/bb
< 200
< Content-Type: application/json

POST /translation/bb
< 200
< Content-Type: application/json

GET /translation/room
< 200
< Content-Type: application/json

POST /translation/room
< 200
< Content-Type: application/json
