<?php $i = 0; ?>
<?php foreach ($this->related as $related): ?>
    <?php if ($i % 3 == 0): ?>
        <div>
        <?php endif; ?>
        <div>
            <div class="float-left margin-right10" style="width:162px;height: 162px;">
                <a href="<?php echo $this->urlDetail($related) ?>"><?php echo $this->writeImage(array('src' => $related->photo, 'width' => 162, 'height' => 162)) ?></a>
            </div>
            <div class="float-left" style="width:184px;">
                <div class="grey font12" style="height: 60px;overflow: hidden">
                    <?php echo substr("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut ligula ipsum, at ultricies ligula. Aliquam element", 0, 250); ?>...
                </div>
                <div class="margin20">
                    <a class="button darkgray" style="width:127px;" href="<?php echo $this->urlDetail($related) ?>"><?php echo l('info') ?></a>
                </div>
                <div class="margin20">
                    <?php echo $this->fbLike($this->url()) ?>
                    <a href="http://pinterest.com/pin/create/button/?url=<?php echo $this->url() ?>&media=<?php echo $this->imageUrl(array('src' => $related->photo, 'width' => 450, 'height' => 275)) ?>&description=<?php echo $related->type . " " . $related->name ?>" class="pin-it-button" count-layout="horizontal"><img border="0" src="//assets.pinterest.com/images/PinExt.png" title="Pin It" /></a>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <?php if (($i + 1) % 3 == 0 || ($i + 1) == count($this->related)): ?>
        </div>
    <?php else: ?>
        <div class="clear" style="margin:20px 0;border-bottom:1px solid #d0dca4;height: 0;width:100%;"></div>
    <?php endif; ?>
    <?php $i++; ?>
<?php endforeach ?>