<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <?php echo $this->headTitle() ?>
        <meta content="" name="description" />        
        <meta content="" name="keywords" />        
        <meta name="language" content="it" />
        <meta name="copyright" content="© 2012 www.adsolut.it - All Rights Reserved" />
        <link rel="icon" type="image/vnd.microsoft.icon" href="/images/favicon.ico?<?php echo rand(1, 99999999) ?>" />
        <link rel="shortcut icon" type="image/x-icon" href="/images/favicon.ico?<?php echo rand(1, 99999999) ?>" />
        <link href='http://fonts.googleapis.com/css?family=Imprima' rel='stylesheet' type='text/css' />
        <link rel="stylesheet" href="/css/jquery-ui-1.8.20.custom.css" type="text/css" media="screen" />
        <link rel="stylesheet" href="/css/style.css" type="text/css" media="screen" />
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="//assets.pinterest.com/js/pinit.js"></script>
        <script type="text/javascript" src="/js/modernizer.js"></script>
        <script type="text/javascript" src="/js/jquery.mousewheel.js"></script>
        <script type="text/javascript" src="/js/jquery.cycle.js"></script>
        <script type="text/javascript" src="/js/jquery.jscrollpane.min.js"></script>
        <script type="text/javascript" src="/js/jqeury.easing.1.3.js"></script>
        <script type="text/javascript" src="/js/facebox.js"></script>
        <script type="text/javascript" src="/js/validate.js"></script>
        <script type="text/javascript" src="/js/jquery.spritely.js"></script>
        <script type="text/javascript" src="/js/jquery.idTabs.min.js"></script>
        <script type="text/javascript" src="/js/jquery.selectbox-0.2.min.js"></script>
        <script type="text/javascript" src="/js/jquery.confirm.js"></script>
        <script type="text/javascript" src="/js/raphael.js"></script>
        <script type="text/javascript" src="/js/AllerDisplay_400.font.js"></script>
        <script type="text/javascript" src="/js/hole.js"></script>
        <script type="text/javascript" src="/js/lightbox.js"></script>
        <script type="text/javascript" src="/js/ready.js?<?php echo rand(1, 999999999) ?>"></script>
        <?php echo $this->headScript() ?>
        <script type="text/javascript" src="https://apis.google.com/js/plusone.js">
            {lang: 'it'}
        </script>
        <script type="text/javascript" src="<?php echo $this->url(array('controller' => 'configuration', 'action' => 'js', 'subdomain' => APPLICATION_SUBDOMAIN)) ?>"></script>
        <script type="text/javascript">
            var baseUrl = '<?php echo $this->url(array('subdomain' => 'admin'), null, true) ?>';
<?php echo $this->placeholder("execScript"); ?>
        </script>
        <script type="text/javascript">

            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-37294262-1']);
            _gaq.push(['_trackPageview']);

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();

        </script>
    </head>
    <body>
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/it_IT/all.js#xfbml=1&appId=233646893428965";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
        <div id="canvas">
            <div id="header">
                <header>
                    <div class="wrapper">
                        <div id="logo">
                            <a data-block href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')) ?>">
                                bed and breakfast offerte, case vacanza offerte, hotel offerte, ostelli offerte, alberghi offerte. 
                            </a>
                        </div>
                    </div>
                </header>
            </div>
            <div id="content">
                <?php echo $this->layout()->content ?>
            </div>
            <!-- comparirà in cima alla pagina -->
            <div id="usefullink">
                <div class="ab_wrapper">
                    <div id="login">
                        <aside>
                            <?php if ($this->currentuser == null): ?>
                                <div id="login-holder">
                                    <ul>
                                        <li id="user-login"><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'index')) ?>"><span></span>login utente</a></li>
                                        <li id="owner-login"><a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'login')) ?>"><span></span>login albergatore</a></li>
                                    </ul>
                                </div>
                            <?php else: ?>
                                <div id="userbadge">
                                    <p id="hi"><?php echo l('Ciao') ?></p>
                                    <p id="name"><a href="<?php echo $this->url(array('controller'=>'admin', 'action'=>"accomodation"))?>"><?php echo $this->currentuser->name ?> <?php echo $this->currentuser->surname ?></a></p>
                                    <p id="user-options clearfix">
                                        <a data-block id="logout" href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'logout')) ?>"><?php echo l('Esci') ?></a>
                                    </p>
                                </div>
                            <?php endif; ?>
                            <div class="clear"></div>
                        </aside>
                    </div>
                    <div id="languages">
                        <aside>
                            <div id="languages_holder">
                                <a id="lang-menu-item" href="">seleziona la lingua<span id="lang-baloon"><img id="selected-flag" class="flag" src="/images/flag_it.jpg"/></span></a>
                                <div id="language-menu">
                                    <ul id="language-item">
                                        <li><a href=""><img src="/images/flag_it.jpg" />italiano</a></li>
                                        <li><a href=""><img src="/images/flag_uk.jpg" />english</a></li>
                                        <li><a href=""><img src="/images/flag_es.jpg" />español</a></li>
                                        <li><a href=""><img src="/images/flag_fr.jpg" />français</a></li>
                                        <li><a href=""><img src="/images/flag_de.jpg" />deutsch</a></li>
                                    </ul>
                                </div>
                            </div>
                        </aside>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
            <div id="social">
                <aside>
                    <div id="social-holder">
                        <div id="fb-like"><iframe src="//www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Fpages%2FBed-And-Breakfast-in-Italy%2F228921990498383&amp;send=false&amp;layout=button_count&amp;width=97&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21&amp;appId=233646893428965" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:97px; height:21px;" allowTransparency="true"></iframe></div>
                        <div id="gp-like"><div class="g-plusone" data-size="medium" data-href="https://plus.google.com/u/0/b/103711838752058855961/103711838752058855961/posts"></div></div>
                    </div>
                </aside>
            </div>
            <!-- /Fine useful -->

            <div id="pusher"></div>
        </div>
        <div id="footer">
            <footer>
                <div class="wrapper">
                    <div id="breadcrumb">
                        <div class="wrapper">
                            <ul>
                                <li><a href="">asd</a></li>
                                <li><a href="">asd</a></li>
                                <li>asd</li>
                            </ul>
                        </div>
                    </div>
                    <div id="copyright">
                        <section>
                            Copyright &copy; 2012 BBItaly <sup>&reg;</sup><br />
                            Tutti i diritti riservati. / <a href="http://www.adsolut.it" target="_blank">web agency napoli</a>
                        </section>
                    </div>
                    <div id="social-pages">
                        <ul>
                            <li id="facebook-page"><a data-block target="_blank" href="https://www.facebook.com/pages/Bed-And-Breakfast-in-Italy/228921990498383"><span></span></a></li>
                            <li id="googleplus-page"><a data-block target="_blank" href="https://plus.google.com/u/0/b/103711838752058855961/103711838752058855961/posts"><span></span></a></li>
                            <li id="twitter-page"><a data-block target="_blank" href="https://twitter.com/BBItaly"><span></span></a></li>
                            <li id="pinterest-page"><a data-block target="_blank" href="https://pinterest.com/bbitaly/"><span></span></a></li>
                        </ul>
                    </div>
                    <div id="cms">
                        <?php if (!empty($this->layout()->cms)):?>
                        <ul>
                            <?php foreach ($this->layout()->cms as $cms) :?>
                                <li><a data-block target="_blank" rel="nofollow" href="<?php echo $this->url(array('controller' => 'cms', 'action' => 'content', 'id' => $cms->id)) ?>"><?php echo $cms->label;?></a></li>
                            <?php endforeach?>
<!--                            <li><a data-block target="_blank" rel="nofollow" href="<?php echo $this->url(array('controller' => 'cms', 'action' => 'chi_siamo')) ?>">Chi siamo</a></li>
                            <li><a data-block target="_blank" rel="nofollow" href="<?php echo $this->url(array('controller' => 'cms', 'action' => 'termini_e_condizioni_d_uso')) ?>">Termini e condizioni d'uso</a></li>
                            <li><a data-block target="_blank" rel="nofollow" href="<?php echo $this->url(array('controller' => 'cms', 'action' => 'privacy')) ?>">Privacy</a></li>-->
                        </ul>
                        <?php endif;?>
                    </div>
                </div>
            </footer>
        </div>  
        <div id="loader_holder">
            <div id="loader" data-frame-width="130" data-width="2600" data-img="/images/loader.png">
                <?php echo l('Caricamento...') ?>
            </div>
        </div>
    </body>
</html>