<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <?php echo $this->headTitle() ?>
        <meta content="" name="description" />        
        <meta content="" name="keywords" />        
        <meta name="language" content="it" />
        <meta name="copyright" content="© 2012 www.adsolut.it - All Rights Reserved" />
        <link rel="icon" type="image/vnd.microsoft.icon" href="/images/favicon.ico?<?php echo rand(1, 99999999) ?>" />
        <link rel="shortcut icon" type="image/x-icon" href="/images/favicon.ico?<?php echo rand(1, 99999999) ?>" />
        <link href='http://fonts.googleapis.com/css?family=Imprima' rel='stylesheet' type='text/css' />
        <link rel="stylesheet" href="/css/style.css" type="text/css" media="screen" />
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="/js/modernizer.js"></script>
        <script type="text/javascript" src="/js/jquery.mousewheel.js"></script>
        <script type="text/javascript" src="/js/jquery.cycle.js"></script>
        <script type="text/javascript" src="/js/jquery.jscrollpane.min.js"></script>
        <script type="text/javascript" src="/js/jqeury.easing.1.3.js"></script>
        <script type="text/javascript" src="/js/facebox.js"></script>
        <script type="text/javascript" src="/js/validate.js"></script>
        <script type="text/javascript" src="/js/jquery.spritely.js"></script>
        <script type="text/javascript" src="/js/jquery.idTabs.min.js"></script>
        <script type="text/javascript" src="/js/jquery.selectbox-0.2.min.js"></script>
        <script type="text/javascript" src="/js/jquery.confirm.js"></script>
        <script type="text/javascript" src="/js/ready.js?<?php echo rand(1, 999999999) ?>"></script>
        <?php echo $this->headScript() ?>
        <script type="text/javascript" src="https://apis.google.com/js/plusone.js">
            {lang: 'it'}
        </script>
        <script type="text/javascript" src="<?php echo $this->url(array('controller' => 'configuration', 'action' => 'js', 'subdomain' => APPLICATION_SUBDOMAIN)) ?>"></script>
        <script type="text/javascript">
            var baseUrl = '<?php echo $this->url(array('subdomain' => 'admin'), null, true) ?>';
<?php echo $this->placeholder("execScript"); ?>
        </script>
        <style>
            html, body {overflow-x:hidden }
        </style>
    </head>
    <body id="terms">
        <div id="canvas">
            <div id="content">
                <div class="wrapper">
                    <?php echo $this->layout()->content ?>
                </div>
            </div>
        </div>
    </body>
</html>