<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <?php echo $this->headTitle() ?>
        <meta content="" name="description" />        
        <meta content="" name="keywords" />        
        <meta name="language" content="it" />
        <meta name="copyright" content="© 2012 www.adsolut.it - All Rights Reserved" />
        <link rel="icon" type="image/vnd.microsoft.icon" href="/images/favicon.ico?<?php echo rand(1, 99999999)?>" />
        <link rel="shortcut icon" type="image/x-icon" href="/images/favicon.ico?<?php echo rand(1, 99999999)?>" />
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="js/ready.js"></script>
    </head>
    <body>
        <?php echo $this->layout()->content?>
    </body>
</html>