<div id="userupdateform">
    <div class="usericon-green"></div>
    <form class="validate" id="form" 
          method="post" 
          data-submit-type="ajax" 
          data-error-container="error_handler"
          data-success-message="<?php echo l('informazioni aggiornate con successo')?>" 
          action="<?php echo $this->url(array('action' => 'updateprocess', 'format' => 'json'))?>">
        <fieldset>
            <p class="relative"><label><?php echo l('nome') ?>&nbsp;<sup>*</sup></label><input name="name" id="owner_name" type="text" value="<?php echo $this->currentuser->name ?>" class="required"/></p>
            <p class="relative"><label><?php echo l('cognome') ?>&nbsp;<sup>*</sup></label><input name="surname" id="owner_surname" type="text" value="<?php echo $this->currentuser->surname ?>" class="required"/></p>
            <p class="relative"><label><?php echo l('email') ?>&nbsp;<sup>*</sup></label><input name="email" id="owner_email" type="text" value="<?php echo $this->currentuser->email ?>" class="required email"/></p>
            <p class="relative"><label><?php echo l('password') ?></label><input name="password" id="password" type="password" /></p>
            <p class="relative"><label><?php echo l('conferma password') ?></label><input name="c_password" id="c_password" type="password" /></p>
            <p class="relative"><input type="submit" value="<?php echo l('invia') ?>"/></p>
            <p class="relative"><label>*<?php echo l('campi obbligatori')?></label></p>
        </fieldset>
    </form>
</div>