<html>
    <head>
        <meta charset="UTF-8" />
    </head>
    <body>
        <table style="width:600px;border-collapse:collapse;">
            <tr>
                <td style="text-align: center;background-color:#eee;padding:27px 0">
                    <a style="color:#666;text-decoration:none" href="http://beta.bedandbreakfastinitaly.com"><img src="http://beta.bedandbreakfastinitaly.com/images/logo.png"/></a>
                </td>
            </tr>
            <tr>
                <td style="background-color:#eee;font-size: 18px;text-align: center;font-style: italic;color:#666;font-family:'Georgia'">
                </td>
            </tr>
            <tr>
                <td style="background-color:#eee;font-size: 24px;text-align: center;font-style: italic;font-weight: bold;color:#666;font-family:'Georgia'">
                    Ciao [nome]
                </td>
            </tr> 
            <tr>
                <td style="background-color:#eee;font-size: 24px;text-align: center;font-style: italic;font-weight: bold;color:#666;font-family:'Georgia';padding:18px 0;">
                    <a style="color:#666;text-decoration:none" href="http://beta.bedandbreakfastinitaly.com"><img src="http://beta.bedandbreakfastinitaly.com/images/email-separator.jpg"/></a>
                </td>
            </tr>
            <tr>
                <td style="background-color:#eee;font-size: 16px;text-align: left;font-style: italic;color:#666;font-family:'Georgia';padding:0px 40px 20px ;">
                    <a style="color:#666;text-decoration:none" href="http://beta.bedandbreakfastinitaly.com">Il Team di BBItaly &egrave; lieto di informarti che nei primi giorni del 2013 il portale sar&agrave; di nuovo on line, con l&apos;obiettivo di accogliere tutte le strutture precedentemente iscritte e le nuove strutture desiderose di visibilit&agrave; e di un contatto diretto ed efficace con gli utenti.<br />
                    <br />
                    Essendo stato un nostro cliente in passato, &egrave; per noi molto importante la tua struttura ed  abbiamo in gran conto l&apos;esperienza da te maturata, intendendo garantirti un servizio completo, innovativo e soprattutto rivolto al futuro.<br />
                    <br />
                    Il nuovo sito – accompagnato da una rinnovata immagine ed un approccio completamente web 2.0 – si propone di diventare il punto di incontro fra strutture ricettive e turisti viaggiatori in cerca di un&apos;ospitalit&agrave; calda ed amichevole, cultura, novit&agrave; e soprattutto convenienza.<br />
                    <br />
                    La possibilit&agrave; per le strutture registrate di ottenere vantaggi &egrave; enorme!<br />
                    BBItaly consentir&agrave; ai Bed and Breakfast iscritti al network di raggiungere gli utenti in maniera immediata, &apos;social&apos;, rendendo il processo di fidelizzazione efficace e costante.<br />
                    L&apos;iscrizione &egrave; gratuita e con solo il 10% su ogni prenotazione ricevuta tramite il nostro portale, garantirai alla tua struttura una visibilit&agrave; senza precedenti.<br />
                    <br />
                    La gestione del profilo su BBItaly sar&agrave; veloce, facile e interattiva, consentendoti di modificare i dati del tuo Bed and Breakfast in tempo reale ogni volta che vuoi!<br />
                    <br />
                    Clicca qui per procedere agilmente ed in maniera guidata alla registrazione ed all&apos;inserimento delle informazioni relative alla tua struttura sul portale.<br />
                    <br />
                    Il 2013 sar&agrave; un anno di rinascita e di incremento dell&apos;economia; questo &egrave; quello che ci auguriamo e che ci prefiggiamo con la nostra professionalit&agrave;.<br />
                    <br />
                    Non aspettare, registra la tua struttura ed inizia a far parte del network!<br />
                    <br />
                    Per qualunque informazione, commento o suggerimento non esitare a contattarci.<br />
                    <br />
                    Cogliamo l&apos;occasione per augurarti uno splendido inizio di anno insieme a tutti noi di BBItaly!<br /></a>
                </td>
            </tr> 
            <tr>
                <td style="background-color:#eee;font-size: 18px;text-align: left;font-style: italic;font-weight: bold;color:#333;font-family:'Georgia';padding: 0;">
                    <a style="color:#666;text-decoration:none" href="http://beta.bedandbreakfastinitaly.com"><img src="http://beta.bedandbreakfastinitaly.com/images/email-footer.jpg"/></a>
                </td>
            </tr>
            <tr>
                <td style="background-color:#333;font-size: 12px;text-align: center;color:#999;font-family:'Arial';padding:0 20px 20px">
                    <a style="color:#999;text-decoration:none" href="http://beta.bedandbreakfastinitaly.com">BBItaly &egrave; un marchio registrato di BBItaly S.r.l.<br />P.iva 07276361214 - tutti i diritti riservati - all rights reserved &copy;2012</a>
                </td>
            </tr>
        </table>
    </body>
</html>