<div class="info-container">
    <?php if ($this->status == 'error'): ?>
        <?php echo $this->partial('block/error.phtml', array('errors' => $this->errors)); ?>
    <?php endif; ?>
    <form class="validate" method="post" action="<?php echo $this->url(array('action' => 'bbupdateprocess')); ?>">
        <fieldset class="essential">
            <p class="description">
                <?php echo l('In questa sezione potrai inserire le informazioni essenziali, i servizi e le policy della tua struttura') ?>
            </p>
        </fieldset>
    </form>
    <form class="validate" method="post" action="<?php echo $this->url(array('action' => 'bbupdateprocess')); ?>">
        <fieldset class="essential">
            <h2>
                <?php echo l('Informazioni essenziali') ?>
            </h2>
            <p><label form="assignedname"><?php echo l('Nome del responsabile') ?></label><input id="assignedname" class="required" name="assignedname" type="text" name="#" /></p>
            <p><label for="propertyname"><?php echo l('nome della struttura') ?></label><input name="propertytname" class="required" id="propertytname" type="text" name="#"/></p>
            <p><label for="phonenumber "><?php echo l('numero di telefono') ?></label><input name="phonenumber" class="required" id="phonenumber" type="text" name="#" /></p>
            <p><label fro="personalemail"><?php echo l('email di contatto') ?></label><input name="personalemail" class="required" id="personalemail" type="text" name="#"/></p>
            <p>
                <label><?php echo l('Provincia') ?></label>
                <select data-source="<?php echo $this->url(array('subdomain' => 'www', 'controller' => 'system', 'action' => 'city', 'format' => 'json')) ?>" data-target="owner_city" id="owner_region" name="region" class="required">
                    <option value="">--</option>
                    <?php foreach ($this->regions as $region): ?>
                        <option value="<?php echo $region->id ?>"><?php echo $region->name ?></option>
                    <?php endforeach; ?>
                </select>
            </p>
            <p>
                <label><?php echo l('Comune') ?>&nbsp;</label>
                <select id="owner_city" name="cityid" class="required">
                    <option value="">--</option>
                    <?php foreach ($this->cities as $city): ?>
                        <option value="<?php echo $city->id ?>"><?php echo $this->accomodation->owner->city->name ?></option>
                    <?php endforeach; ?>
                </select>
            </p>
            <p>
                <label><?php echo l('indirizzo') ?></label>
                <input name="address" id="owner_address" class="required" type="text" />
            </p>
        </fieldset>
        <fieldset class="contact">
            <h2>
                <?php echo l('descrizione struttra') ?>
            </h2>
            <p>
                <label><?php echo l('Tipologia struttura') ?></label>
                <select id="type" name="type" class="required">
                    <option value="bedbreakfast" <?php echo $this->accomodation->type == 'bedbreakfast' ? 'selected="selected"' : '' ?>><?php echo l('Bed and Breakfast') ?></option>
                    <option value="hotel" <?php echo $this->accomodation->type == 'hotel' ? 'selected="selected"' : '' ?>><?php echo l('Hotel') ?></option>
                    <option value="Appartamento" <?php echo $this->accomodation->type == 'Appartamento' ? 'selected="selected"' : '' ?>><?php echo l('Appartamento') ?></option>
                    <option value="monolocale" <?php echo $this->accomodation->type == 'monolocale' ? 'selected="selected"' : '' ?>><?php echo l('monolocale') ?></option>
                    <option value="Chalet" <?php echo $this->accomodation->type == 'Chalet' ? 'selected="selected"' : '' ?>><?php echo l('Chalet/baita') ?></option>
                    <option value="villa" <?php echo $this->accomodation->type == 'villa' ? 'selected="selected"' : '' ?>><?php echo l('Casa/villa') ?></option>
                    <option value="Dimora_tipica" <?php echo $this->accomodation->type == 'Dimora_tipica' ? 'selected="selected"' : '' ?>><?php echo l('Dimora tipica') ?></option>
                    <option value="Rustico" <?php echo $this->accomodation->type == 'Rustico' ? 'selected="selected"' : '' ?>><?php echo l('Rustico') ?></option>
                    <option value="Agriturismo" <?php echo $this->accomodation->type == 'Agriturismo' ? 'selected="selected"' : '' ?>><?php echo l('Agriturismo') ?></option>
                    <option value="mobil_home" <?php echo $this->accomodation->type == 'mobil_home' ? 'selected="selected"' : '' ?>><?php echo l('Mobil home') ?></option>
                    <option value="Barca" <?php echo $this->accomodation->type == 'Barca' ? 'selected="selected"' : '' ?>><?php echo l('Barca a vela') ?></option>
                    <option value="yatch" <?php echo $this->accomodation->type == 'yatch' ? 'selected="selected"' : '' ?>><?php echo l('Yacht') ?></option>
                </select>
            </p>
            <p>
                <label><?php echo l('Lingua') ?></label>
                <select id="desclang" name="desclang" class="required">
                    <?php foreach ($this->langs as $lang): ?>
                        <option value="<?php echo $lang ?>" <?php if ($lang == $this->currentLang): ?>selected="selected"<?php endif; ?>><?php echo $lang ?></option>
                    <?php endforeach; ?>
                </select>
            </p>
            <p>
                <textarea id="description" class="required" name="description"></textarea>
            </p>
            <br class="clear"/>
        </fieldset>
        <fieldset class="facility">
            <h2>
                <?php echo l('Servizi') ?>
            </h2>
            <?php foreach ($this->facility as $name => $facility): ?>
                <label class="title">
                    <div class="clear"></div>
                    <?php
                    switch ($name) {
                        case 1:
                            echo l('Piscina');
                            break;
                        case 2:
                            echo l('Frigobar');
                            break;
                        case 3:
                            echo l('Struttura');
                            break;
                        case 4:
                            echo l('Letti');
                            break;
                        case 5:
                            echo l('Mq abitabili');
                            break;
                        case 6:
                            echo l('Mq giardino');
                            break;
                        case 7:
                            echo l('Sicurezza');
                            break;
                        case 8:
                            echo l('Attrezzature');
                            break;
                        case 9:
                            echo l('Servizi addizionali');
                            break;
                        case 10:
                            echo l('Cucina');
                            break;
                        case 11:
                            echo l('Svago');
                            break;
                        case 12:
                            echo l('Esterno');
                            break;
                        case 13:
                            echo l('Idromassaggio');
                            break;
                        case 14:
                            echo l('Computer');
                            break;
                        case 15:
                            echo l('Servizi generali');
                            break;
                    }
                    ?>
                </label>
                <div class="clear"></div>
                <?php $i = 0 ?>
                <?php foreach ($facility as $option): ?>
                    <span class="checkbox">
                        <input type="checkbox" <?php if ($option['selected'] || $i == 0): ?>checked="checked"<?php endif; ?> value="<?php echo $option['id'] ?>" name="facilitiesId[]" /><label><?php echo $option['name'] ?></label>
                    </span>
                <?php endforeach; ?>
            <?php endforeach; ?>
            </p>
        </fieldset>
        <fieldset class="policy">
            <h2>
                <?php echo l('Policy') ?>
            </h2>
            <?php foreach ($this->policy as $name => $policy): ?>
                <?php $i = 0 ?>
                <?php foreach ($policy as $option): ?>
                    <span class="checkbox" style="width:auto">
                        <input type="checkbox" <?php if ($option['selected'] || $i == 0): ?>checked="checked"<?php endif; ?> value="<?php echo $option['id'] ?>" name="policyId[]" /><label><?php echo $option['name'] ?></label>
                    </span>
                    <br class="clear" />
                    <?php if (++$i % 2 == 0): ?>
                        <!--                        <br class="clear" />-->
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endforeach; ?>
            </p>
        </fieldset>
        <fieldset class="submit lastelement">
            <input type="submit" value="<?php echo l('procedi') ?> &gt;&gt;"/>
        </fieldset>
    </form>
</div>