<?php
echo $this->adminLeftcolumn(array(
    'books' => array(
        'action' => 'books',
        'active' => false,
        'label' => l('Prenotazioni')
    ),
    'accomodations' => array(
        'action' => 'accomodation',
        'active' => true,
        'label' => l('I miei annunci')
    ),
    'configuration' => array(
        'action' => 'settings',
        'active' => false,
        'label' => l('Configurazioni')
    )
));
?>
<div class="wcenter-outer-container clearfix">
    <div class="wcenter-outer">
        <div class="wcenter-inner">
            <?php
            $url = array(
//                'settings' => array(
//                    'url' => $this->url(array('action' => 'invoice', 't' => '0')),
//                    'active' => false,
//                    'label' => l('fatture saldate')
//                ),
                'seo' => array(
                    'url' => $this->url(array('action' => 'invoice', 't' => '1')),
                    'active' => true,
                    'label' => l('fatture pendenti')
                )
            );
            foreach ($this->cms as $index => $cm) {
                $url['url' . $index] = array(
                    'url' => $this->url(array('action' => 'invoice', 't' => 'cms', 'c' => $cm->id)),
                    'active' => false,
                    'label' => $cm->label
                );
            }
            ?>
            <?php
            echo $this->adminLeftcolumn($url);
            ?>
        </div>
    </div>
</div>
<form action="<?php echo $this->url(array('action' => 'invoiceupdate')) ?>" method="post">
    <div id="invoiceTab" class="tab">
        <div class="desc">
            Il sistma VerySign Secured<sup>&REG;</sup> garantisce la gestione dei tuoi dati in maniera completamente protetta.
        </div>
        <div class="full-width-column title">
            <h2 class="nomargin"><?php echo l('Anagrafica') ?></h2>
        </div>
        <div class="half-width-column">
            <p>
                <label form="invoice_title">
                    <?php echo l('titolo') ?>
                </label>
                <select id="invoice_title" class="required" name="invoice[salutation]" type="text">
                    <option><?php echo l('Sig.') ?></option>
                    <option><?php echo l('Sig.ra') ?></option>
                </select>
            </p>
            <p>
                <label for="invoice_name">
                    <?php echo l('nome e cognome') ?>
                </label>
                <input class="required" name="invoice[invoice_name]" value="<?php echo isset($this->invoiceData['invoice_name']) ? $this->invoiceData['invoice_name'] : '' ?>" id="invoice_name" type="text"/>
            </p>
            <p>
                <label for="invoice_surname">
                    <?php echo l('codice fiscale / partita i.v.a.') ?>
                </label>
                <input class="required" name="invoice[invoice_vat]" value="<?php echo isset($this->invoiceData['invoice_surname']) ? $this->invoiceData['invoice_surname'] : '' ?>" id="invoice_surname" type="text"/>
            </p>
            <p>
                <label for="invoice_email">
                    <?php echo l('email') ?>
                </label>
                <input class="required"  name="invoice[invoice_email]" value="<?php echo isset($this->invoiceData['invoice_email']) ? $this->invoiceData['invoice_email'] : '' ?>" id="invoice_email" type="text"/>
            </p>
        </div>
        <div class="half-width-column">
            <p>
                <label><?php echo l('Provincia') ?></label>
                <p id="invoice_region_holder">
                    <select class="required" onchange="$(this).parent().next().val($(this).find(':selected').text())" tabindex="5" data-holder="#invoice_region_holder" name="invoice[invoice_owner_region]" data-source="http://demo.bella-idea.com/it/system/city" data-target="#invoice_owner_city" id="invoice_owner_region" name="invoice_region" class="required">
                        <?php foreach ($this->regions as $regions): ?>
                            <option value="<?php echo $regions->id ?>"><?php echo $regions->name ?></option>
                        <?php endforeach ?>
                    </select>
                </p>
                <input type="hidden" name="invoice[invoice_owner_region_name]"/>
            </p>
            <p>
                <label><?php echo l('Comune') ?>&nbsp;</label>
            <p id="invoice_city_holder">
                <select tabindex="4" data-holder="#invoice_city_holder" name="invoice[invoice_owner_city]" id="invoice_owner_city" name="invoice_city" class="required"></select>
            </p>
            </p>
            <p>
                <label for="invoice_address">
                    <?php echo l('indirizzo') ?>
                </label>
                <input name="invoice[invoice_address]" value="<?php echo isset($this->invoiceData['invoice_address']) ? $this->invoiceData['invoice_address'] : '' ?>" class="" id="invoice_address" type="text"/>
            </p>
            <p>
                <label for="invoice_zip">
                    <?php echo l('C.A.P. / zip code') ?>
                </label>
                <input class="" name="invoice[invoice_zip]" value="<?php echo isset($this->invoiceData['invoice_zip']) ? $this->invoiceData['invoice_zip'] : '' ?>" id="invoice_zip" type="text"/>
            </p>
        </div>
        <div class="clear"></div>
        <div class="full-width-column title">
            <h2><?php echo l('Carta di Credito') ?></h2>
        </div>
        <div class="clear"></div>
        <div class="half-width-column">
            <p>
                <label for="invoice_cc">
                    <?php echo l('numero della carta di credito') ?>
                </label>
                <input class="" name="invoice[invoice_cc]" value="<?php echo isset($this->invoiceData['invoice_cc']) ? $this->invoiceData['invoice_cc'] : '' ?>" id="invoice_cc" type="text"/>
            </p>
            <p>
                <label for="cc_owner">
                    <?php echo l('intestatario della carta di credito') ?>
                </label>
                <input class="" name="invoice[cc_owner]" value="<?php echo isset($this->invoiceData['cc_owner']) ? $this->invoiceData['cc_owner'] : '' ?>" id="cc_owner" type="text"/>
            </p>
            <p>
                <label for="personalemail">
                    <?php echo l('accettiamo le seguenti carte di credito') ?>
                </label>
                <img src="/images/ccaccepted.png" />
            </p>
        </div>
        <div class="half-width-column">

            <p>
                <label for="cc_expire">
                    <?php echo l('data di scadenza della carta di credto') ?>
                </label>
                <input name="invoice[cc_expire]" value="<?php echo isset($this->invoiceData['cc_expire']) ? $this->invoiceData['cc_expire'] : '' ?>" class="" id="cc_expire" type="text"/>
            </p>
            <p>
                <label for="cc_security">
                    <?php echo l('CVC / CVV / CID') ?>
                </label>
                <input name="invoice[cc_security]" value="<?php echo isset($this->invoiceData['cc_security']) ? $this->invoiceData['cc_security'] : '' ?>" class="" id="cc_security" type="text"/>
            </p>
            <p>
                <br />
                <br />
                <img src="/images/verysign.png" />
            </p>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
        <div class="full-width-column">
            <div>
                <input id="save" type="submit" value="<?php echo l('modifica') ?>"/>
            </div>
        </div>
    </div>
</form>
<div class="clear"></div>
<script>
    $(function() {
        $('form').forms();
    })
</script>