<script>
    $(function() {
        $( "#gallery-container" ).sortable({
            placeholder: "gallery-highlight"
        });
        $( "#gallery-container" ).disableSelection();
    });
</script>
<div class="wcenter-outer-container">
    <div class="wcenter-outer">
        <div class="wcenter-inner">
            <div id="stepslist">
                <ul class="clearfix" data-tab-container="#tabContent">
                    <li id="contacts" class=""><a href="<?php echo $this->url(array('action' => 'bbupdate')) ?>"><?php echo l('info') ?></a></li>
                    <li id="contacts" class="active"><a href="<?php echo $this->url(array('action' => 'photogallery')) ?>"><?php echo l('foto') ?></a></li>
                    <li id="contacts" class=""><a href="<?php echo $this->url(array('action' => 'updatepolicy')) ?>"><?php echo l('servizi e policy') ?></a></li>
                    <li id="contacts" class=""><a href="<?php echo $this->url(array('action' => 'translation')) ?>"><?php echo l('descrizioni') ?></a></li>
                    <li id="contacts" class=""><a href="<?php echo $this->url(array('action' => 'prices')) ?>"><?php echo l('prezzo') ?></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div style="height: 50px"></div>
<div class="info-container">
    <fieldset>
        <div style="float:left">
            <label><?php echo l('Carica la gallery per la tua struttura') ?></label>
            <?php echo $this->uploader("upload", 'refreshPhotoList') ?>
        </div>
        <div style="float:right">
            <label><?php echo l('Carica la foto di copertina della tua struttura') ?></label>
            <?php echo $this->uploader('cover', null, 1, 'bb-cover') ?>
        </div>
        <div class="clear"></div>
    </fieldset>
</div>
<div id="photocontainerstatic" class="info-container" data-id="<?php echo $this->bbid ?>">
    <?php echo $this->partial('block/gallery.phtml', array('id' => $this->bbid, 'type' => $this->type, 'photos' => $this->photos, 'errors' => $this->errors)) ?>
</div>