<div class="addroom">
    <div>
        <a href="<?php echo $this->url(array('action' => 'roomcreate')) ?>"><?php echo l('Aggiungi nuova stanza') ?></a>
    </div>
</div>
<?php foreach ($this->rooms as $item): ?>
    <div class="accomodation-container">
        <div class="accomodation">
            <div class="photo">
                <?php if (empty($this->cover) && empty($this->cover[$item->id])):?>
                    <?php echo $this->writeImage(array('type' => 'room', 'src' => null, 'width' => 200, 'height' => 150)); ?>
                <?php else:?>
                    <?php echo $this->writeImage(
                            array(
                                'type' => 'room', 'src' => $this->cover[$item->id]->url, 'width' => 200, 'height' => 150)); ?>
                <?php endif;?>
            </div>
            <div class="info">
                <h3>
                    <?php echo $item->shortDescription ?>
                </h3>
                <p>
                    <?php echo $item->generalDescription ?>
                </p>
            </div>
            <div class="clear"></div>
        </div>
        <div class="options">
            <a class="update" href="<?php echo $this->url(array('action' => 'roomupdate','id' => $this->id, 'rid' => $item->id)) ?>"><?php echo l('info') ?></a>
            <a class="delete" rel="ajax" href="<?php echo $this->url(array('action' => 'deleteroom', 'id' => $item->id)) ?>"><?php echo l('delete') ?></a>
        </div>
        <div class="clear"></div>
    </div>
<?php endforeach ?>