<?php
/**
 * Implements hook_block_info().
 *
 * This function tells drupal about our block.
 *
 
 */
function registration_block_info() {
        // Create an array that will hold our blocks
        $blocks = array();
 
        // Create a key in our $blocks array that
        // defines our block.  Note that the key in
        // this array can be anything.  For this
        // tutorial, we  use 'tellafriend_form'.
        $blocks['registration_form'] = array(
                // 'info' is what you will see when viewing the blocks admin page.
                // Note that we use the t() (translate) function which lets drupal
                // translate any text passed in if needed.
                'info' => t('Registration'),
                // 'cache' how this block will be cached
                'cache' => DRUPAL_CACHE_GLOBAL,
        );
 
        // Note, if you wanted to define multiple blocks, you 
        // could simply define more blocks just like above.
 
        // Finally, we return the $blocks array.
        return $blocks;
}
 
/**
 * Implements hook_block_view().
 * 
 * This function tells drupal how to define our block when viewed.
 *
 *
 */
 
function registration_block_view($delta = '') {
        // Create an array that will be returned as our block
        $block = array();
 
        // Since hook_block_view is called for every block,
        // Drupal passes in $delta (the key of the blocks defined
        // in hook_block_info.  In our case, we're checking for
        // $delta to be 'tellafriend_form'.
        switch($delta) {
                case 'registration_form':
                        // Since this $delta matches our case, we'll define
                        // the subject and contents.
 
                        // 'subject' can be blank ('') or anything you wish to define.
                        $block['subject'] = t('Tell A Friend');
 
                        // 'content' are just that, the contents of the block.
                        // In our case, we will be showing a form.
                        // We use drupal_get_form() to return a drupal-built form.
                        // Note that the parameter passed to drupal_get_form is the name
                        // of the function we will build below to define our form.
                        // This can be any function name we define below.
                        $block['content'] = drupal_get_form('registration_form');
                break;
        }
 
        // Finally, we return the $block array.
        return $block;
}
 
/**
 * Define the form to be returned.
 *
 * Note that drupal passes in two parameters,
 * $form - which holds all of the elements of the form
 * $form_state - a special array of settings & values needed by Drupal
 */
function registration_form($form, &$form_state) {
        // Now the fun begins.  For this simple example,
        // we will only provide two form elements.
        // 1. an input for the friend's email address
        // 2. a submit button
        // You can add as much or as little to this form as
        // needed.  See the forms api for all possible elements.
 
      /*  $form['friends_email'] = array(
                // #type tells drupal what kind of element to build
                '#type' => 'textfield',
                // we want this field to be required
                '#required' => TRUE,
                // The "label" for this field
                '#title' => t("Your friend's email address"),
                // Optional description
                '#description' => t('Must be a valid email address'),
        );*/
		$form['content']=array(
			'#prefix'=>'<div id="whole">',
		);
		$form['name']=array(
			 '#type' => 'textfield',
			  '#required' => TRUE,
			  '#title' => t("Name"),
			  '#size' => '40',
			  '#prefix'=> '<div id="errorwrapper1">',
			  '#suffix'=>'</div>',
		);
		
		$form['surname']=array(
			 '#type' => 'textfield',
			  '#required' => TRUE,
			  '#title' => t("Surname"),
			  '#size' => '40',
		);
		
		$form['E-mail']=array(
			 '#type' => 'textfield',
			  '#required' => TRUE,
			  '#title' => t("E-mail"),
			  '#size' => '40',
		);
		
		$form['confirm_email']=array(
			 '#type' => 'textfield',
			  '#required' => TRUE,
			  '#title' => t("Confirm E-mail"),
			  '#size' => '40',
		);
		
		$form['accetto']=array(
				'#type'=>'checkbox',
				'#required' => TRUE,
				'#title' => t("Acceto i termini cancellazione,le regole della casa,le condizioni di rimborso all'opsite e i termini del servizio"),
				'#attributes'=>array(
					'class'=>array('clearfix'),
				),
		
		);
		
 
        $form['submit'] = array(
                '#type' => 'submit',
                // #value is the text to display inside the button
                '#value' => t('Register'),
		'#suffix'=>'</div>',
		'#attributes' => array(
					'class' => array('clearfix'),								
				),
				"#ajax" => array(
						  "callback" => "registration_form_callback", 
						  "wrapper" => "whole", 
						  "effect" => "fade",
						),
        );
 
        return $form;
}

function registration_form_callback($form, &$form_state) {
	
	/*form['name']['attributes']['class']= 'red-background'*/
	if(!empty($form_state['executed'])){
			return '<div id="block-registration-registration-form" style="background-color:#D4E6BE"><div id="whole" style="background-color:#D4E6BE;">'.t("<h1>Congratulation!</h1>").'<br><p id="welcome_msg">'.t("Now you can book on <b>BBITALY your holidays</b>!").'<br>'.'Have a good trip!'.'</p>'.'<a class="homepage_link" href="http://crtvecode.com/bbnew">'.t("Back to homepage").'</a><br>'.'<p id="mail_notofication">'.t("Shortly recieve an email with your username and password needed to access the portal as hotelier").'</p>'.'</div></div>';
	  }
	/*else{
			$name=$form['values']['name'];
			if(empty($name)){
				return '<div id="whole"><div id="errorwrapper1" style="color:red">'.t("name is required").drupal_render($form).'</div></div>';
			}
	}*/
  return '<div id="whole">'.drupal_render($form).'</div>';
}



/* function registration_form_validate($form, &$form_state) {
  if ($form_state['values']['name'] == '') {
   form_set_error('', t('Name field is empty!'));
  }
}

function registration_form_submit($form, &$form_state) {
  drupal_set_message(t('Your form has been saved.'));
} */
 
/*
 * Define a validation function that drupal will
 * automatically call when the submit button is pressed.
 *
 * For this example, I will use the valid_email_address()
 * function to verify that the email address looks
 * proper.  If it's not, we'll use form_set_error()
 * function to tell drupal we didn't pass validation.
 */
function registration_form_validate($form, &$form_state) {
        // Drupal stows away all of the form elements into
        // $form_state['values'].  We find our 'friends_email'
        // element and assign it to a variable for easy
        // reference.
        $email = $form_state['values']['E-mail'];
		$confirm_mail=$form_state['values']['confirm_email'];
 
        // If it's not a valid email, set an error.
        if(valid_email_address($email) == 0) {
                // form_set_error() tells drupal that it should not proceed.
                // The first parameter is the form element that didn't pass
                // validation.  The second is the message to tell the user.
               /* form_set_error('E-mail', t('Not a valid email address'));*/
			  
        }
		
		if($email!=$confirm_mail){
			form_set_error('confirm_email',t('Invalid confirm E-mail'));
		}
}


/*
 * Define a submit funciton that drupal will
 * automatically call when submit is pressed (and all validators pass)
 */
function registration_form_submit($form, &$form_state) {
		//drupal_set_message(t('Thanks for registering in bbitaly'));
		
	$edit = array(
    'name' => $form_state['values']['name'],
    'surname' => $form_state['values']['surname'],
	'pass'=> user_password(8),
    'mail' => $form_state['values']['E-mail'],
    'init' => $form_state['values']['confirm_email'],
    'status' => 1,
    'access' => REQUEST_TIME,
	$roles = array('5' => 'Traveller'),
    'roles' => $roles,
  );
  
     $account = new stdClass();
     $account->is_new = TRUE;
    $user=user_save($account,$edit);
	$user->password=$edit['pass'];
	
	_user_mail_notify('register_no_approval_required',$user);
	
	
}

/**
 * Implements hook_mail().
 */
/*function registration_mail($key, &$message, $params) {
        // Get the url for this site
        global $base_url;
        // Set the subject for this email.
        $message['subject'] = t('bbitaly');
       // Set the body. Note how we use a token in the t() function to hold our
        // link (!link) and then tell drupal the !link = $base_url.
        $message['body'][] = t("Hello,\nYour friend thought you might like this site.  Please click the link below to visit.\n\n!link", array('!link' => $base_url));
}*/

/**
 * Implements hook_token_info().
 * */
function registration_token_info() {
    $info['tokens']['user']['password'] = array(
    'name' => t('Password'),
    'description' => t('The password by the user'),
    );
return $info;
}

/**
 * Implements hook_tokens().
 * */
function registration_tokens($type, $tokens, array $data = array(), array $options = array()) {
   $replacements = array();
		
    /*$url_options = array('absolute' => TRUE);
    if (isset($options['language'])) {
        $url_options['language'] = $options['language'];
    }*/
    if ($type == 'user' && !empty($data['user'])) {
        $account = $data['user'];
        foreach ($tokens as $name => $original) {
            switch ($name) {
                case 'password':
                     $original = $account->name . ': ' . $account->password;
                    break;
            }
        }
    }
    return $replacements;
}
?>
 