
<div id="breadcrumb">
    <a class="font-gray font12" href="<?php echo $this->url(array('language' => $this->language, 'subdomain' => 'www'), null, true) ?>">home</a> <span class="font12 font-gray">/</span> <span class="font12 font-gray"><?php echo $this->title?></span>
</div>
<div style="height: 20px;"></div>
<div class="section ac">
    <h3>
        <?php echo $this->title ?>
    </h3>
    <p clasS="font-gray font12">
        <?php echo $this->paragraph ?>
    </p>
</div>
<div style="height: 20px;"></div>
