<div id="cms-container" class="clearfix">
    <h3>1. Privacy</h3>
    <ul>
        <li>1.1 BBItaly S.r.l. con sede in Napoli alla via Francesco Verrotti n. 6, 80128, &egrave; custode dei dati personali comunicati dagli Utenti al momento della registrazione e/o dell&apos;iscrizione che sono trattati nel rispetto delle norme di cui al d.lgs. 30 giugno 2003, n. 1961.
            I dati personali comunicati dagli Utenti sono trattati per soddisfare le richieste degli utenti stessi (registrazione, iscrizione e prenotazione di alloggi o vacanze) ed in ogni caso per l&apos;invio della Newsletter periodica all&apos;indirizzo e-mail indicato al momento dell&apos;iscrizione o della registrazione.
        </li><li>1.2.Il conferimento dei dati personali da parte dell&apos;Utente &egrave; puramente volontario, e costituisce condizione indispensabile, a seconda dei casi, per l&apos;iscrizione, la registrazione o l&apos;effettuazione di transazioni attraverso il sito Web. I predetti dati vengono trattati sia in formato elettronico sia in via telematica, con modalit&agrave; e strumenti volti a garantire la massima sicurezza e riservatezza e vengono resi accessibili esclusivamente da personale di BBItaly S.r.l. debitamente incaricato al trattamento. 
            I dati personali comunicati dagli utenti non saranno in alcun caso diffusi o venduti, ma potranno essere comunicati - per finalit&agrave; connesse all&apos;esecuzione delle richieste degli utenti - a terzi appartenenti alle seguenti categorie: - soggetti che forniscono servizi per la gestione del sistema informativo e delle reti di telecomunicazioni di BBItaly S.r.l.   societ&agrave; che svolgono servizi di incasso e pagamento mediante carte di credito; soggetti che svolgono adempimenti di controllo, revisione e certificazione delle attivit&agrave; poste in essere da BBItaly S.r.l. anche nell&apos;interesse degli utenti.
        </li>
        <li>
            1.3 Gli utenti potranno rivolgersi a  BBItaly S.r.l.  per far valere i diritti riconosciuti in favore degli interessati dall&apos;art. 7 del D. Lgs. n. 196/03 ("L&apos;interessato ha diritto di ottenere la conferma dell&apos;esistenza o meno di dati personali che lo riguardano, anche se non ancora registrati, e la loro comunicazione in forma intelligibile.<br />
        </li>
        <li>
            1.3.2. L&apos;interessato ha diritto di ottenere l&apos;indicazione:
            <ul>
                <li>
                    a) dell&apos;origine dei dati personali;
                </li>
                <li>
                    b) delle finalita&apos; e modalita&apos; del trattamento;
                </li>
                <li>
                    c) della logica applicata in caso di trattamento effettuato con l&apos;ausilio di strumenti elettronici;
                </li>
                <li>
                    d) degli estremi identificativi del titolare, dei responsabili e del rappresentante designato ai sensi dell&apos;articolo 5, comma 2;
                </li>
                <li>
                    e) dei soggetti o delle categorie di soggetti ai quali i dati personali possono essere comunicati o che possono venirne a conoscenza in qualita&apos; di rappresentante designato nel territorio dello Stato, di responsabili o incaricati.
                </li>
            </ul>
        <li>
            1.3.3. L&apos;interessato ha diritto di ottenere:
            <ul>
                <li>
                    a) l&apos;aggiornamento, la rettificazione ovvero, quando vi ha interesse, l&apos;integrazione dei dati;
                </li>
                <li>
                    b) la cancellazione, la trasformazione in forma anonima o il blocco dei dati trattati in violazione di legge, compresi quelli di cui non e&apos; necessaria la conservazione in relazione agli scopi per i quali i dati sono stati raccolti o successivamente trattati;
                </li>
                <li>
                    c) l&apos;attestazione che le operazioni di cui alle lettere a) e b) sono state portate a conoscenza, anche per quanto riguarda il loro contenuto, di coloro ai quali i dati sono stati comunicati o diffusi, eccettuato il caso in cui tale adempimento si rivela impossibile o comporta un impiego di mezzi manifestamente sproporzionato rispetto al diritto tutelato.                    
                </li>
            </ul>
        </li>
        <li>
            1.3.4. L&apos;interessato ha diritto di opporsi, in tutto o in parte:
            <ul>
                <li>
                    a) per motivi legittimi al trattamento dei dati personali che lo riguardano, ancorche&apos; pertinenti allo scopo della raccolta;
                </li>
                <li>
                    b) al trattamento di dati personali che lo riguardano a fini di invio di materiale pubblicitario o di vendita diretta o per il compimento di ricerche di mercato o di comunicazione commerciale")                    
                </li>
            </ul>
        </li>
    </ul>
</li>
<li>
    Le relative richieste andranno inviate via email all&apos;indirizzo info@bbItaly.com  o lettera raccomandata con avviso di ricevimento all&apos;indirizzo BBItaly S.r.l. con sede in Napoli alla via Francesco Verrotti n. 6, 80128.
</li>
</ul>
</div>