<div id="cms-container" class="clearfix">
    <h2>Condizioni Generali e Termini d'uso</h2>
    <h3>1. Condizioni Generali e Termini d’uso.</h3>
    <ul>
        <li>1.1. BBItaly S.r.l. con sede in Napoli alla via Francesco Verrotti n. 6, 80128, P.IVA 07276361214, Iscritta alla Camera di commercio di Napoli, proprietaria del Network  BBItaly.com composto dai domini web: www.bbitaly.com - www.bbitalia.com - www.bedandbreakfastinitaly.com - www.bedandbreakfastinitalia.com (di seguito definita BBItaly.com), svolge un’attività di commercio on line consistente nel fornire un collegamento diretto tra strutture alberghiere rientranti nella tipologia “bed and breakfast, affittacamere, case vacanza, residence, agriturismi” (di seguito definiti Partners) e utenti interessati ad effettuare prenotazioni on line presso la struttura prescelta tra quelle registrate sul sito BBItaly.com (di seguito definiti Clienti).
            BBItaly S.r.l. fornisce altresì servizi di pubblicità e visibilità alle strutture interessate in occasione di particolari eventi, in determinati periodi dell’anno. 
            Le presenti Condizioni Generali e Termini d’uso disciplinano unicamente: le modalità di fornitura del servizio di collegamento tra le strutture alberghiere sopra identificate e la clientela attuato da BBItaly S.r.l.  attraverso la pubblicazione nel proprio sito di materiale identificativo e informativo sulle strutture registrate, offerte speciali ed ogni altra attività promozionale che il Partner voglia offrire; la predisposizione di un sistema di prenotazione per i clienti interessati ad alloggiare nelle strutture registrate nel sito BBItaly.com</li>
        <li>1.2. Per quanto non espressamente previsto dalle presenti Condizioni Generali e Termini d’uso si rimanda, oltre che alla normativa contrattuale, alle norme che disciplinano l’attività delle strutture definite bed and breakfast, affittacamere, case vacanza, residence, agriturismi, nonché alle condizioni legali per transazioni SEPA per la parte relativa ai pagamenti.</li>
    </ul>
    <h3>2. Modalità del servizio offerto.</h3>
    <ul>
        <li>
            Il servizio offerto da BBItaly S.r.l. consiste nel selezionare e pubblicizzare sul proprio sito le strutture bed and breakfast, affittacamere, case vacanza, residence, agriturismi presenti sul territorio nazionale capaci di offrire al Cliente il miglior rapporto prezzo/qualità tra quelle presenti nell’ambito territoriale prescelto, così da facilitare e velocizzare la scelta dei Clienti.
            Attraverso l’utilizzo del motore di ricerca BBItaly.com il Cliente potrà ricevere in tempo reale informazioni sulle strutture alberghiere partendo dalla zona di interesse del proprio soggiorno (ad es. Via Tasso, Napoli) e conoscere immediatamente quali sono i migliori bed and breakfast, affittacamere, case vacanza, residence, agriturismi presenti nella zona di interesse; a questo punto il Cliente potrà servirsi del sistema di prenotazione BBItaly per prenotare direttamente il proprio soggiorno, in maniera veloce, facile e trasparente.
        </li>
    </ul>
    <h3>3. Registrazione.</h3>
    <ul>
        <li>
            3.1.La registrazione al sito BBItaly.com è completamente gratuita, sia per il Partner che per il Cliente.
        </li>
        <li>
            3.2.Ciascun Partner (identificato come struttura bed and breakfast, affittacamere, case vacanza, residence, agriturismi) per poter fruire dei servizi, deve aver eseguito correttamente la procedura di registrazione riservata alla propria categoria e, quindi, aver fornito le proprie credenziali registrate (email e password) che saranno utilizzate per la procedura di autenticazione, oltre che le informazioni identificative dell’impresa, come richieste nel  paragrafo “Registrazione e utilizzo del servizio per il Partner”.
            Il Partner, una volta eseguita la registrazione, può utilizzare gli strumenti presenti sul sito per pubblicare informazioni sulla propria struttura, assumendo la responsabilità circa la completezza e veridicità delle informazioni fornite, anche in relazione all’uso improprio di immagini e marchi, ed avendo cura di aggiornare periodicamente i dati al fine di garantire la rispondenza al vero delle informazioni fornite. In caso di violazione, BBItaly si riserva il diritto di bloccare l’uso del sito per il Partner, fatte salve le ulteriori conseguenze di legge.
        </li>
        <li>
            3.3.Il Partner si impegna a pagare una commissione a BBItaly S.r.l. calcolata nella misura del 10% + iva da ricevere al momento del check-out per ogni prenotazione pagata, secondo le modalità di cui al paragrafo 7.2 del contratto di adesione tra il Partner e BBItaly S.r.l. contenuto nell’allegato A, che forma parte integrante del presente documento e che, con l’accettazione delle presenti condizioni generali e termini d’uso, s’intendono dal Partner anch’esse visionate e accettate.
        </li>
    </ul>
    <h3>4. Prenotazione.</h3>
    <ul>
        <li>4.1.Il sistema di prenotazione on-line BBItaly.com per il Cliente è completamente gratuito. Ogni Cliente potrà accedere liberamente al sito BBItaly.com e consultare le informazioni ivi presenti, anche attraverso gli appositi strumenti di ricerca, visualizzando i dettagli delle offerte e potrà effettuare direttamente la prenotazione del proprio alloggio compilando l’apposito modulo (allegato B)</li>
        <li>4.2.Il Cliente che abbia scelto di prenotare un bed and breakfast, affittacamere, case vacanza, residence, agriturismi tramite il sistema di prenotazione di BBItaly.com dovrà fornire i propri dati identificativi come richiesti dal sistema (account, email e password) e potrà effettuare una prenotazione che sarà inoltrata direttamente da BBItaly.com al Partner titolare della struttura.
            La scheda identificativa del Cliente, completa dei dati dallo  stesso forniti, sarà visibile unicamente al Cliente ed al Partner titolare della struttura prescelta dal Cliente, oltre che alla BBItaly s.r.l</li>
        <li>4.3.Il Partner si impegna a comunicare preventivamente al Cliente ed a BBItaly S.r.l. ogni modifica riguardante le e condizioni e modalità di pagamento rispetto a quelle elencate nel presente documento e di applicare le stesse solo in caso di espressa accettazione dell’altra parte.</li>
        <li>4.4.Il Partner si impegna altresì a fornire tempestivamente a BBItaly. S.r.l., che ne darà comunicazione sul proprio sito, tutte le informazioni relative alla disponibilità delle stanze, alle variazioni sul servizio offerto, alle modifiche last minute delle condizioni di alloggio offerte e prenotate, al pericolo di over-booking e under-booking tenendo indenne la BBItaly S.r.l. da ogni danno dovesse essere arrecato ai Clienti per una di queste ipotesi o ipotesi similari.</li>
        <li>4.5.Il contratto di alloggio tra Partner e Cliente si perfeziona secondo le suindicate modalità. Per tutte le obbligazioni nascenti dal contratto tra Partner e Cliente si rimanda al contratto di fornitura di alloggio stipulato direttamente tra le parti e perfezionato con il pagamento della prenotazione, con declino di ogni responsabilità della BBItaly s.r.l per ogni tipo di inadempimento tra le parti e per ogni tipo di danno prodotto alle stesse in ragione del contratto stesso, fatto salvo unicamente il dovere di ordinaria vigilanza sui contenuti e l’utilizzo del sito attuato da BBItaly S.r.l.</li>
    </ul>
    <h3>5. Pagamento</h3>
    <ul>
        <li>5.1. La prenotazione di un alloggio attraverso il sistema BBItaly.com è gratuita.</li>
        <li>5.2. All’atto della prenotazione,  e solo se richiesto dalla struttura prescelta, il Cliente potrà essere tenuto a versare un anticipo, o a pagare l’intero soggiorno (in caso, ad esempio,  di offerte speciali)  secondo le modalità preventivamente comunicate dal Partner all’atto della prenotazione e pubblicate a cura del Partner sul sito BBItaly.com nella scheda informativa della struttura.</li>
        <li>5.3 Il Cliente effettuerà la prenotazione presso la struttura prescelta inserendo, in piena e assoluta sicurezza, i dati della propria Carta di Credito o prepagata in modo che la struttura stessa possa verificarne la disponibilità.
            Il pagamento effettivo della tariffa per la prenotazione pubblicata sul sito BBItaly.com, così come il pagamento del prezzo per l’intero soggiorno prenotato avverrà direttamente presso la struttura prescelta. 
            Di conseguenza al momento del check-out BBItaly S.r.l. avrà diritto a ricevere dal Partner la commissione del 10% + iva come meglio specificato al paragrafo 7 del <a href="<?php echo $this->url(array('controller'=>'cms','action'=>'contratto_adesione_partner'))?>">MODULO A</a>.
            In ogni caso i dati della Carta di Credito o prepagata forniti dal Cliente all’atto della prenotazione dell’alloggio verranno inviati alla struttura prescelta attraverso il sito BBItaly.com dotato del certificato di sicurezza Verisign.
            Il sito BBItaly.com invierà una email al Partner contenente gli estremi della avvenuta prenotazione, estremi verificabili da parte della struttura stessa all’interno dell’area a sè riservata. I dati della Carta di Credito o prepagata in essa contenuti rimangono visibili per 72 ore dal momento della prenotazione, e dalla data di check-in fino a sette giorni dopo la data di check-out. </li>
        </li>
        <li>5.4 Per ogni prenotazione effettuata, il Cliente riceverà una mail di conferma dal sito BBItaly.com.</li>
    </ul>
    <h3>6. Recesso e cancellazione</h3>
    <ul>
        <li>Il Cliente che abbia effettuato una prenotazione attraverso il sito BBItaly.com potrà sempre cancellare la stessa, senza conseguenze ulteriori, salvo penali per la cancellazione che siano richieste dal Partner e delle quali il Cliente sia messo preventivamente a conoscenza all’atto della Prenotazione.
            Sia il Partner che il Cliente potranno in ogni momento cancellare la propria registrazione dal sito BBItaly.com, senza alcuna conseguenza di legge, fatti salvi, per il Partner, gli obblighi derivanti dal contratto di adesione sottoscritto con BBItaly S.r.l. di cui all’allegato A.
            L’ Utente iscritto e/o registrato al sito BBItaly.com accetta che BBItaly S.r.l. possa disattivare l’account e la password o interrompere il servizio fornito per qualunque motivo, con o senza preavviso e senza incorrere in alcuna responsabilità per tale ragione.
        </li>
    </ul>

    <h3>7. Condizioni contrattuali</h3>
    <ul>
        <li>
            Per l’analisi in dettaglio delle condizioni contrattuali pattuite tra gli utenti del servizio BBItaly.com si rimanda al:
            Allegato A: contratto di adesione tra Partner e BBItaly
            Allegato  B: modulo di  prenotazione del Cliente
        </li>
    </ul>
    <h3>8. Garanzie degli utenti.</h3>
    <ul>
        <li>8.1.Le presenti condizioni generali di contratto contengono i termini d’uso e le condizioni generali che regolano la fornitura dei servizi offerti da BBItaly S.r.l. ai Partners registrati nel proprio sito e i Clienti che effettuano prenotazioni attraverso il sistema BBItaly.com e sono disponibili e consultabili all’indirizzo http://www.bbitaly.com/condizionigenerali.
            BBItaly S.r.l. può modificare le condizioni generali e i termini d'uso pubblicandone sul sito http://www.bbitaly.com/condizionigenerali l'aggiornamento, che verrà considerato come implicitamente accettato qualora l’utente continui ad utilizzare il sito successivamente alle modifiche stesse e non faccia pervenire entro cinque giorni lavorativi una dichiarazione di non accettazione delle modifiche a mezzo email o lettera raccomandata a.r. all’indirizzo della BBItaly S.r.l.. </li>
        <li>8.2. Con l’accettazione delle presenti condizioni generali ed i termini d’uso l’utente dichiara, sotto la propria responsabilità: 
            <ul>
                <li>a) di aver letto e compreso le condizioni generali ed i termini d’uso; </li>
                <li>b) di essere maggiorenne, di avere la capacità di agire e sottoscrivere contratti legalmente vincolanti;</li>
                <li>c) che si asterrà dal riprodurre, duplicare, copiare, vendere, rivendere e comunque sfruttare a fini commerciali il Sito o il Servizio o una qualunque loro parte, nonchè dal riprodurre o utilizzare in qualsiasi modo i marchi ed i loghi di BBItaly S.r.l.  o del sito BBItaly.com;</li>
                <li>d) che non pubblicherà o utilizzerà dati falsi, calunniosi o diffamatori; </li>
                <li>e) che si asterrà da ogni forma di utilizzo, diretto e/o indiretto, del Servizio e del Sito contrario alla legge o non conforme a quanto previsto nelle presenti condizioni generali e termini d’uso o nel sito www.bbitaly.com;</li>
                <li>f) che si asterrà dall'immettere nel Sito qualsiasi contenuto osceno, offensivo, violento, diffamatorio, pornografico e pedo-pornografico, lesivo della dignità personale; informazioni o messaggi che istruiscano su attività illegali, inducano a attività illegali o che possano causare pregiudizio a terzi; incitamenti a comportamenti pericolosi e a rischio emulazione da parte di minori o all'uso di droghe o al maltrattamento di animali; messaggi, anche occulti, di natura promozionale e/o pubblicitaria; immagini non adatte ai minori di anni 18;</li>
                <li>g) che non utilizzerà sistemi di c.d. spamming, di messaggi a catena o di vendita piramidale;</li>
                <li>h) che non diffonderà virus informatici;</li>
                <li>i) che non utilizzerà software o altri meccanismi automatici o manuali per copiare o accedere alle pagine del Sito o al loro contenuto.
                    BBItaly S.r.l. declina ogni responsabilità per la violazione delle suindicate clausole posta in essere dagli utenti del sito, fatta salva la facoltà di adire le vie legali qualora riscontrasse la commissione di violazioni in tal senso.</li>
            </ul>
        </li>
    </ul>
    <h3>9. Clausola di salvaguardia utente e sistema valutazione attraverso feedback</h3>
    <ul>
        <li>9.1La registrazione al sito http://www.bbitaly.com, sia in qualità di Partner che di Cliente, e l’utilizzo effettivo del servizio avvengono attraverso la compilazione di appositi moduli che contengono con chiarezza le indicazioni circa le modalità di svolgimento del servizio, le condizioni precontrattuali e contrattuali che vengono accettate cliccando la casella ACCETTO  in calce alle presenti dichiarazioni.</li>
        <li>9.2Ai sensi e per gli effetti degli obblighi di trasparenza e chiarezza nelle comunicazioni commerciali di cui all’art. 52 del d. lgs. n. 206 del 06.12.2005 (Codice del Consumo), nonché del Dlgs n° 50/92 in materia di contratti negoziati fuori dei locali commerciali e del Dlgs n°185/99 sulla protezione dei consumatori in materia di contratti a distanza, le informazioni identificative fornite dai Partners ai fini della loro registrazione e le condizioni legali applicate dai software di pagamento utilizzati, salvi gli obblighi derivanti dalla legge sulla privacy, sono pubblicate sul sito BBItaly.com e visionabili a tutti con la conseguenza che l’accettazione delle stesse da parte degli Utenti - attraverso la registrazione al sito - manleva BBItaly.com per ogni danno diretto, indiretto  e consequenziale prodotto agli utenti dall’utilizzo del servizio fornito da soggetti terzi rispetto a BBItaly s.r.l.
            BBItaly S.r.l.. declina ogni responsabilità per usi fraudolenti del servizio fornito attraverso il portale http://www.bbitaly.com </li>
        <li>9.3 Ogni utente del sito potrà esprimere valutazioni in relazione al servizio offerto da BBItaly.com nell’apposito form di gradimento visibile sul sito nell’apposita pagina, attraverso il sistema dei feedback che consentirà immediatamente ad ogni Utente di verificare la migliore struttura sulla base delle valutazioni dei Clienti.
            Al fine di garantire l’Utente del servizio offerto da BBItaly S.r.l., sia come Partner sia come Cliente, BBItaly si riserva il diritto di pubblicare nel suindicato form anche segnalazioni circa eventuali inadempimenti rispetto elle violazioni delle presenti condizioni generali (nonché di quelle contenute negli allegati A e B) </li>
        <li>9.4 Se un Partner riceve più di tre segnalazioni negative da parte del Cliente, BBItaly S.r.l.  si riserva il diritto di cancellarlo immediatamente dal sito, sospendendo il sistema di prenotazioni in suo favore ed inserendo il nominativo del Partner tra le “Strutture sconsigliate”.
            Accettando tale clausola il Partner viene inserito in un sistema di  visibilità delle informazioni e trasparenza delle comunicazioni commerciali come garanzia di tutela della buona fede nelle transazioni commerciali e fatte salve le prescrizioni di cui alla legge n. 675/1996  e del d.lgs. 30 giugno 2003, n. 1961,e successive modifiche ed integrazioni,  in tema di privacy.</li>
    </ul>
    <h3>10. Contratto per il servizio di alloggio.</h3>
    <ul>
        <li>10.1 Il Partner si impegna a fornire tutte le informazioni relative alla disponibilità delle stanze, ai prezzi, ai servizi offerti, alle offerte speciali, alla cancellation policy, ed ad aggiornarle continuamente. 
            Tramite il sito BBItaly.com il Partner ed il Cliente possono stipulare tra loro un contratto avente ad oggetto esclusivamente l’alloggio nella struttura. 
            Ogni Partner ha facoltà di indicare le modalità prescelte per la prenotazione e per il successivo perfezionarsi del contratto di alloggio all’atto della pubblicazione nel sito BBItaly delle informazioni relative alla propria struttura.</li>
        <li>10.2 Fatta salva la concorde volontà tra le parti di disciplinare diversamente il loro accordo, il contratto di alloggio si intende perfezionato nel momento della conferma da parte della struttura della prenotazione effettuata dal Cliente, inoltrata attraverso il sistema BBItaly.com.
            Il Cliente, infatti,  compilando l’apposito <a href="<?php echo $this->url(array('controller'=>'cms','action'=>'condizioni_cliente'))?>">MODULO B</a> predisposto dal sistema prenotazione BBItaly.com effettuerà una prenotazione che sarà inoltrata  dal sistema direttamente al Partner titolare della struttura; il cliente si impegna a rispettare le modalità di pagamento (anticipo o meno) richieste dal Partner e pubblicate nell’offerta di alloggio presso la struttura prescelta.
        </li><li>10.3 Il Partner si impegna a comunicare preventivamente al Cliente ed a BBItaly S.r.l. ogni modifica riguardante le e condizioni e modalità di pagamento rispetto a quelle elencate nel presente documento e di applicare le stesse solo in caso di espressa accettazione dell’altra parte.
            In ogni caso, i dati della Carta di Credito o prepagata forniti dal Cliente all’atto della prenotazione dell’alloggio verranno inviati alla struttura prescelta attraverso il sito  BBItaly.com dotato del certificato di sicurezza Verisign. 
            Il sito BBItaly.com invierà una email al partner contenente gli estremi della avvenuta prenotazione, estremi verificabili da parte della struttura stessa nell’area a sè riservata. 
            I dati della Carta di Credito in essa contenuti rimangono visibili per 72 ore dal momento della prenotazione, e dalla data di check-in fino a 7 giorni dopo la data di check-out. 
        </li><li>10.4 Per il recesso del Cliente rispetto alla prenotazione di un alloggio presso un Partner registrato al sito BBItaly.com e, si rimanda all’apposito <a href="<?php echo $this->url(array('controller'=>'cms','action'=>'contratto_adesione_partner'))?>">MODULO A</a> (applicabilità norme codice consumo in combinato disposto con gli artt.55 comma 1 lett. b), 64 e 65 del D.lgs. 6 settembre 2005, n. 205 che consentono l’esercizio del recesso solamente nei termini di cui all’art.9 lett h del d. lgs n. 111/1995, in presenza di servizio di alloggio offerto in vendita ad un prezzo forfettario e della durata superiore a due notti.)
            Le modalità dell’esercizio del diritto di recesso sono quelle di cui agli artt. 64 e 65 del Codice del Consumo (entro dieci giorni  lavorativi dalla proposta contrattuale con l’invio alla sede del Partner di una comunicazione scritta mediante lettera raccomandata con avviso di ricevimento, o telegramma, fax, telex, posta elettronica, a condizione che sia confermata mediante lettera raccomandata con avviso di ricevimento entro le 48 ore successive)</li>
    </ul>
    <h3>11. Responsabilità</h3>
    <ul>
        <li>11.1 L'Utente riconosce ed espressamente accetta che:
            il Sito raccoglie materiale informativo e offerte di alloggio delle strutture registrate e raccoglie prenotazioni in dette strutture effettuate da Clienti; BBItaly S.r.l. non assume direttamente o indirettamente alcun obbligo di contrattare e concludere accordi di alcun tipo con l'Utente o con terzi;
            BBItaly S.r.l. agisce da mero intermediario tra i Partner e i Clienti, al fine esclusivo di far incontrare domanda e offerta in relazione all’alloggio presso strutture alberghiere nella tipologia bed and breakfast, affittacamere, case vacanza, residence, agriturismi presenti in una determinata zona.
            I Clienti sono l'unica controparte contrattuale dei Partner e BBItaly S.r.l. è totalmente estranea ai contratti di alloggio stipulati e perfezionati tra le parti e non ha alcun controllo sulle offerte provenienti dai Partners, che assumono preventivamente ogni responsabilità in tal senso.
        </li><li>11.2 Considerato quanto previsto al punto precedente, BBItaly S.r.l. non rilascia alcuna dichiarazione o garanzia al singolo acquirente circa la veridicità, la correttezza e la completezza delle informazioni fornite dai Partners, anche per ciò che concerne le informazioni da rendersi obbligatoriamente ai consumatori ai sensi della legge applicabile, il corretto adempimento delle obbligazioni e delle promesse dei Partners, la titolarità delle strutture Bed and breakfast la capacità dei Partners di disporne. In ogni caso BBItaly S.r.l. farà del proprio meglio per controllare e verificare ciascun Partner, ferma la possibilità per gli utenti del sito procedere direttamente ad effettuare ogni verifica e segnalarla a BBItaly S.r.l. attraverso il sistema dei feedback e dei questionari.
        </li><li>11.3 Fatto salvo il caso di dolo o colpa grave, nella massima misura consentita dalla legge, il Partner riconosce ed accetta che BBItaly S.r.l non sarà in alcun modo responsabile verso il Cliente  per eventuali danni, perdite, costi, oneri e spese, diretti o indiretti, incluse le eventuali spese legali, subiti e/o sopportati dal Cliente in ragione dell’alloggio effettuato o prenotato presso la propria struttura e/o, in ogni caso, in connessione con il Servizio  fornito da BBItaly S.r.l. ai sensi delle condizioni generali e dei termini d’uso. 
            BBItaly S.r.l. non sarà in alcun modo responsabile verso i Partners o i Clienti per eventuali ritardi o inadempimenti alle proprie obbligazioni.
            BBItaly S.r.l. non è responsabile per danni cagionati da virus informativi che potrebbero infettare l’equipaggiamento dell’utilizzatore del computer.
        </li><li>11.4 L’Utente riconosce ed accetta che tutti i contenuti, servizi e  prodotti offerti sul presente sito, comprendendo in essi anche i servizi e le garanzie derivanti dagli strumenti di pagamento forniti da terze parti (ad es. transazioni SEPA) e per i quali si rimanda alle rispettive condizioni contrattuali in particolare in riferimento alle modalità di conservazione e trasmissione dei dati trasmessi a dette parti, con esclusione di ogni e qualsivoglia  responsabilità per BBItaly S.r.l. o i suoi dipendenti, vengono forniti da BBItaly S.r.l. “come tali” senza alcuna garanzia, esplicita o implicita, ivi comprese quelle relative a commerciabilità, idoneità per uno scopo particolare, non contraffazione, destinazione di applicazione ed uso, fatto salvo l’ordinario dovere di vigilanza sui contenuti pubblicati e l’utilizzo del sito.</li>
    </ul>
    <h3>12. Privacy</h3>
    <ul>
        <li>12.1 BBItaly S.r.l. con sede in Napoli alla via Francesco Verrotti n. 6, 80128, è custode dei dati personali comunicati dagli Utenti al momento della registrazione e/o dell'iscrizione che sono trattati nel rispetto delle norme di cui al d.lgs. 30 giugno 2003, n. 1961.
            I dati personali comunicati dagli Utenti sono trattati per soddisfare le richieste degli utenti stessi (registrazione, iscrizione e prenotazione di alloggi o vacanze) ed in ogni caso per l'invio della Newsletter periodica all'indirizzo e-mail indicato al momento dell'iscrizione o della registrazione.
        </li><li>12.2.Il conferimento dei dati personali da parte dell'Utente è puramente volontario, e costituisce condizione indispensabile, a seconda dei casi, per l'iscrizione, la registrazione o l'effettuazione di transazioni attraverso il sito Web. I predetti dati vengono trattati sia in formato elettronico sia in via telematica, con modalità e strumenti volti a garantire la massima sicurezza e riservatezza e vengono resi accessibili esclusivamente da personale di BBItaly S.r.l. debitamente incaricato al trattamento. 
            I dati personali comunicati dagli utenti non saranno in alcun caso diffusi o venduti, ma potranno essere comunicati - per finalità connesse all'esecuzione delle richieste degli utenti - a terzi appartenenti alle seguenti categorie: - soggetti che forniscono servizi per la gestione del sistema informativo e delle reti di telecomunicazioni di BBItaly S.r.l.   società che svolgono servizi di incasso e pagamento mediante carte di credito; soggetti che svolgono adempimenti di controllo, revisione e certificazione delle attività poste in essere da BBItaly S.r.l. anche nell'interesse degli utenti.
        </li>
        <li>12.3 Gli utenti potranno rivolgersi a  BBItaly S.r.l.  per far valere i diritti riconosciuti in favore degli interessati dall'art. 7 del D. Lgs. n. 196/03 (“L'interessato ha diritto di ottenere la conferma dell'esistenza o meno di dati personali che lo riguardano, anche se non ancora registrati, e la loro comunicazione in forma intelligibile.2. L'interessato ha diritto di ottenere l'indicazione:
            <ul>
                <li>
                    a) dell'origine dei dati personali;
                </li>
                <li>
                    b) delle finalita' e modalita' del trattamento;
                </li>
                <li>
                    c) della logica applicata in caso di trattamento effettuato con l'ausilio di strumenti elettronici;
                </li>
                <li>
                    d) degli estremi identificativi del titolare, dei responsabili e del rappresentante designato ai sensi dell'articolo 5, comma 2;
                </li>
                <li>
                    e) dei soggetti o delle categorie di soggetti ai quali i dati personali possono essere comunicati o che possono venirne a conoscenza in qualita' di rappresentante designato nel territorio dello Stato, di responsabili o incaricati.3. L'interessato ha diritto di ottenere:a) l'aggiornamento, la rettificazione ovvero, quando vi ha interesse, l'integrazione dei dati;
                </li>
                <li>
                    b) la cancellazione, la trasformazione in forma anonima o il blocco dei dati trattati in violazione di legge, compresi quelli di cui non e' necessaria la conservazione in relazione agli scopi per i quali i dati sono stati raccolti o successivamente trattati;
                    c) l'attestazione che le operazioni di cui alle lettere a) e b) sono state portate a conoscenza, anche per quanto riguarda il loro contenuto, di coloro ai quali i dati sono stati comunicati o diffusi, eccettuato il caso in cui tale adempimento si rivela impossibile o comporta un impiego di mezzi manifestamente sproporzionato rispetto al diritto tutelato.4. L'interessato ha diritto di opporsi, in tutto o in parte:a) per motivi legittimi al trattamento dei dati personali che lo riguardano, ancorche' pertinenti allo scopo della raccolta;b) al trattamento di dati personali che lo riguardano a fini di invio di materiale pubblicitario o di vendita diretta o per il compimento di ricerche di mercato o di comunicazione commerciale)
                    Le relative richieste andranno inviate via email all’indirizzo info@bbItaly.com  o lettera raccomandata con avviso di ricevimento all'indirizzo BBItaly S.r.l. con sede in Napoli alla via Francesco Verrotti n. 6, 80128.
                </li>
            </ul>
        </li>
    </ul>
    <h3>13. Marchi e proprietà intellettuali</h3>
    <ul>
        <li>
            BBItaly S.r.l. è titolare di ogni diritto relativo al contenuto grafico, editoriale e concettuale del proprio sito, con esclusione dei marchi, segni distintivi e limitazioni relative ai Servizi offerti dai Partners. 
            Sono vietate la modifica, la riproduzione, la pubblicazione anche parziale, del contenuto o degli elementi grafici nonchè il trasferimento a terzi delle informazioni, dei contenuti e delle immagini pubblicate sul sito http://www.BBItaly.com e/o altre utilizzazioni senza il consenso scritto da parte di BBItaly S.r.l.
            BBItaly S.r.l. ha pieno diritto di pubblicare e utilizzare il marchio e/o i segni distintivi dei Partners unicamente in relazione alle esigenze di pubblicità delle rispettive strutture e offerte di alloggio. Successivamente alla conclusione di ogni prenotazione da parte del Cliente, il marchio e/o segno distintivo dei Partners potranno rimanere visibili sul sito www.bbitaly.com nella bacheca dei Partners salvo espressa indicazione contraria da comunicarsi per iscritto ad onere del Partner.
            Il sistema di prenotazione BBItaly.com è di proprietà ed è gestito da BBItaly S.r.l. 
            Tutti i diritti relativi al design delle pagine web, al software, al testo, alla grafica, alla selezione, l’organizzazione e la presentazione degli stessi sono riservati. 
            BBItaly S.r.l. e BBItaly.com sono marchi registrati di proprietà di BBItaly S.r.l.
        </li>
    </ul>
    <h3>14. Diritto applicabile e foro competente</h3>
    <ul>
        <li>
            14.1Le presenti Condizioni Generali e Termini d’uso sono regolati dalla Legge Italiana.
            Per la composizione delle controversie nascenti dall’applicazione del presente contratto tra le parti BBItaly s.r.l ed i Partners queste potranno rivolgersi agli strumenti di conciliazione introdotti con il d. lgs. n.28/2010 predisposti presso la Camera di Commercio di Napoli o ad un collegio arbitrale composto di tre arbitri di cui uno scelto dalla BBItaly S.r.l., uno scelto dal Partner ed un terzo designato di comune accordo tra le parti. In mancanza di accordo sulla scelta del terzo arbitro, questo sarà designato dal Presidente del  Tribunale di Napoli. 
            In alternativa, le parti potranno rivolgersi all’autorità giudiziaria competente che viene identificata, come foro esclusivo, nel Tribunale di Napoli.
        </li>
        <li>
            14.2Per le controversie nascenti dall’applicazione del presente contratto tra le parti BBItaly S.r.l. e gli utenti registrati come Clienti questa si rivolgeranno all’autorità giudiziaria competente che, secondo quanto stabilito dal Codice del Consumo a tutela dei consumatori, prevede la competenza del Foro della residenza o domicilio del consumatore per qualsiasi controversia sorgesse tra le Parti in relazione alla validità, interpretazione, esecuzione e risoluzione delle presenti Condizioni Generali.
        </li>
    </ul>
    <b>ACCETTO LE CONDIZIONI SOPRA INDICATE
        NON ACCETTO LE CONDIZIONI SOPRA INDICATE
        IN CASO di adesione, accetto segnatamente ai sensi dell’art.  1341 comma 2 c.c. le clausole n. 5 (Pagamento), 6 (recesso), 8 (garanzie), 9 (Clausola di salvaguardia e feedback), 11 (responsabilità), 12 (privacy), 14 (Foro competente)
    </b>
</div>